language: java

jdk: oraclejdk8
r: release # https://docs.travis-ci.com/user/languages/r/
addons:
  apt:
    packages:
      - oracle-java8-installer  # https://github.com/travis-ci/travis-ci/issues/3259

install:
  - sudo apt-get install r-base # needed for Rscript
  #- sudo Rscript -e 'install.packages("rjson", repos = "http://cran.r-project.org")'

script: ./run.sh
